### ISSUE TITLE
Improve Legibility of Enumerations

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/json-schema-web-component#2]
**Is your feature request related to a problem? Please describe.**
Difficult to read enumerations (1)...(2)...(3)...

**Describe the solution you'd like**
Should convert text to bullets

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/4313463/48500777-abd4cd80-e809-11e8-95bb-abaee82652bb.png)

**Comment by jcastle-zz** [comment]
Moved this into front-end as a React component and will modify with USWDS in the near future.
