### ISSUE TITLE
Bookmark Line

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/json-schema-web-component#3]
**Is your feature request related to a problem? Please describe.**
It would be a great to store a URL that links to a line in the schema viewer

**Describe the solution you'd like**
Some should be able to share a link to a line. Perhaps using the browser's built-in functionality to scroll to id's that follow hash sign #

**Describe alternatives you've considered**
We could try to do this scrolling in JavaScript and use the web component to listen to page load and popstate events

**Additional context**
I came up with this idea after reading https://github.com/GSA/code-gov-front-end/issues/91#issuecomment-440717279

**Comment by jcastle-zz** [comment]
Moved this into front-end as a React component and will modify with USWDS in the near future.
